package com.tn.softsys.blocoperatoire.domain;

public enum AlertType {
    INTERVENTION_PLANIFIEE,
    INTERVENTION_REPROGRAMMEE,
    INTERVENTION_DEMARREE,
    SSPI_DEPASSEMENT,
    SSPI_DESATURATION,
    SSPI_HYPOTENSION,
    SSPI_HYPERTENSION,
    SSPI_TACHYCARDIA,
    SALLE_ACTIVEE,
    SALLE_DESACTIVEE
}
