ALTER TABLE salles
    ADD COLUMN IF NOT EXISTS statut VARCHAR(40);

UPDATE salles
SET statut = CASE
    WHEN COALESCE(active, FALSE) THEN 'DISPONIBLE'
    ELSE 'FERMEE'
END
WHERE statut IS NULL OR BTRIM(statut) = '';

UPDATE salles
SET active = CASE
    WHEN statut IN ('DISPONIBLE', 'PLANIFIEE', 'EN_INTERVENTION') THEN TRUE
    ELSE FALSE
END
WHERE statut IS NOT NULL;

ALTER TABLE salles
    ALTER COLUMN statut SET NOT NULL;
